const assert = require('assert');
const fs = require('fs');
const vm = require('vm');
const profile = JSON.parse(fs.readFileSync('src/profiles/generic.json', 'utf8'));
const context = { console, window: {}, fetch: async () => ({ ok: true, json: async () => profile }) };
for (const file of ['profile.js', 'app/onboarding.js']) vm.runInNewContext(fs.readFileSync('src/' + file, 'utf8'), context);
(async () => {
    const api = await context.window.WarehouseProfileReady;
    const labels = ['冷冻', '冷藏', 'สินค้าแช่เย็น', 'Café', '📦', '🔋', 'GENERAL'];
    const draft = context.window.WarehouseOnboarding.createDraft({ name: '仓库', categories: labels.map(label => ({ label })) });
    const loaded = await api.load(draft);
    assert.strictEqual(draft.categories[0].id, '冷冻');
    assert.strictEqual(draft.categories[2].id, 'สินค้าแช่เย็น');
    assert.strictEqual(new Set(draft.categories.map(c => c.id)).size, labels.length);
    assert.deepStrictEqual(Array.from(draft.snapshotCategories), draft.categories.slice(0, 4).map(c => c.id));
    assert.strictEqual(loaded.categoryId('Cafe\u0301'), 'café');
    const reordered = context.window.WarehouseOnboarding.createDraft({ categories: labels.slice().reverse().map(label => ({ label })) });
    for (const category of draft.categories) assert.strictEqual(reordered.categories.find(c => c.label === category.label).id, category.id);
    const unknownA = loaded.resolveUnknownCategory('未知甲').id, unknownB = loaded.resolveUnknownCategory('未知乙').id;
    assert.notStrictEqual(unknownA, unknownB);
    assert.strictEqual(unknownA, 'unknown:未知甲');
    assert.notStrictEqual(loaded.resolveUnknownCategory('🧊').id, loaded.resolveUnknownCategory('🧪').id);
    assert.strictEqual(loaded.resolveUnknownCategory('Re\u0301serve').id, loaded.resolveUnknownCategory('Réserve').id);
    const emptyFields = context.window.WarehouseOnboarding.createDraft({ categories: [{}, {}] });
    await api.load(emptyFields);
    assert.deepStrictEqual(Array.from(emptyFields.snapshotCategories), ['category-1', 'category-2']);
    const duplicate = context.window.WarehouseOnboarding.createDraft({ categories: [{ label: 'Café' }, { label: 'Cafe\u0301' }] });
    assert.throws(() => api.validate(duplicate), /duplicate category id/);
    console.log('Unicode category identifier tests passed');
})().catch(error => { console.error(error); process.exitCode = 1; });
